feat: user department api endpoint [DD-20324]
dossierdata/api.documentation pull request #5
Opened 2021-03-10 11:29 UTC by pktromp

- Add UserDepartments 

[DD-20324]

2021-03-22 10:37 UTC, lucasvdh requested changes
![image](https://user-images.githubusercontent.com/4311594/111977410-fade4c00-8b02-11eb-920a-829d6c9ee574.png)

2021-03-22 10:37 UTC, lucasvdh commented on dossierdata.v1.openapi.yaml
> +          $ref: '#/components/responses/UserDepartmentResponse'
`components/responses/UserDepartmentResponse` bestaat nog niet

2021-03-22 10:37 UTC, lucasvdh commented on dossierdata.v1.openapi.yaml
> +        - $ref: '#/components/parameters/UserDepartmentId'
`components/parameters/UserDepartmentId` bestaat nog niet

2021-03-22 10:37 UTC, lucasvdh commented on dossierdata.v1.openapi.yaml
> +                  $ref: '#/components/schemas/UserDepartments'
`components/schemas/UserDepartments` bestaat nog niet

2021-03-22 12:02 UTC, lucasvdh requested changes
Ook mis ik volgens mij nog de `show` endpoint die één enkele user department terug geeft.

2021-03-22 12:02 UTC, lucasvdh commented on dossierdata.v1.openapi.yaml
> +      name: userDepartment_id
Dit moet gelijk zijn aan de param in de url `user_department_id`

![image](https://user-images.githubusercontent.com/4311594/111986852-bfe21580-8b0e-11eb-8ded-e38750214c5f.png)

2021-03-22 12:14 UTC, pktromp commented
> Ook mis ik volgens mij nog de `show` endpoint die één enkele user department terug geeft.

zie regel 3383

2021-03-22 12:16 UTC, lucasvdh commented on dossierdata.v1.openapi.yaml
> +        - Address
Ah kijk, dit is waarom ik hem niet zag waar ik hem zou verwachten.

2021-03-24 11:30 UTC, lucasvdh approved these changes, later dismissed

2021-03-24 11:33 UTC, lucasvdh requested changes

2021-03-24 11:33 UTC, lucasvdh commented on dossierdata.v1.openapi.yaml
> +          user_id: 1
Example komt niet overeen met de Schema. Hier mist het `id` attribuut.

2021-03-24 11:33 UTC, lucasvdh commented on dossierdata.v1.openapi.yaml
> +            user_id: 1
Example komt niet overeen met de Schema. Hier mist het `id` attribuut

2021-03-24 11:58 UTC, lucasvdh approved these changes

2021-03-24 11:58 UTC, merged